name: Build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Release]
        os: [windows-latest]

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Build
          cake-bootstrap: true
